### PR TITLE
Rc june to dev 2022.06.28

### PR DESCRIPTION
**Pull request by BeniaminDrasovean**

### CODE REVIEW

**Review by iulianpascalau — CHANGES_REQUESTED** [review]
I think we need a new indexer version compatible with the development branch. @miiu96 , can you help us?

**Comment by miiu96** [comment]
Changed the indexer version

**Comment by miiu96** [comment]
> I think we need a new indexer version compatible with the development branch. @miiu96 , can you help us?

Changed the indexer version

**Review by iulianpascalau — APPROVED** [review]

**Review by miiu96 — APPROVED** [review]

**Review by bogdan-rosianu — APPROVED** [review]

**Review by andreibancioiu — APPROVED** [review]

**Review by gabi-vuls — APPROVED** [review]
System test passed.

**Pull request merged**
