### PR TITLE
[FOR TESTS] Chaotic / malicious transactions pool

### PR DESCRIPTION
**Pull request by andreibancioiu**

### CODE REVIEW

**Comment by elrondscammer3** [comment]
Crooked sons of bitches. Give us our money back.
 BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ER

**Comment by elrondscammer3** [comment]
Crooked sons of bitches. Give us our money back.
 BTC dump ERD dump BTC pump ERD dump BTC stable ERD dump. Don'T buy ER

**Comment by elrondscammer2** [comment]
Elrond was HACKED! Big dump

**Comment by elrondscammer2** [comment]
That's enough!! Cheating bastards.
The price keeps falling. People don't trust you. ERD doesn't buy. What do you boys do for a living?

**Pull request closed without merging**
