### PR TITLE
Integrate arwen rc1

### PR DESCRIPTION
**Pull request by sasurobert**
Integrated Arwen RC1 to elrond-go

### CODE REVIEW

**Review by iulianpascalau — COMMENTED** [review]
We need to ensure that these changes are backwards compatible

**Review by iulianpascalau — CHANGES_REQUESTED** [review]
Missing description

**Review by SebastianMarian — APPROVED** [review]

**Review by SebastianMarian — APPROVED** [review]

**Review by iulianpascalau — DISMISSED** [review]
Pending import-db tests...

**Review by iulianpascalau — APPROVED** [review]

**Review by SebastianMarian — APPROVED** [review]

**Review by LucianMincu — APPROVED** [review]
System tests passed.

**Pull request merged**
